services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - path: ./.postgres.env
        required: true
    ports:
      - "5432:5432"
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - personal_finances_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: personal_finances_app
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - path: ./.app.env
        required: true
    volumes:
      - ./app:/app
    networks:
      - personal_finances_network

networks:
  personal_finances_network:
    name: personal_finances_network
    driver: bridge