// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: incomes.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIncome = `-- name: CreateIncome :one
INSERT INTO incomes (user_id, category_id, income_date, amount, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, category_id, income_date, amount, description, created_at, updated_at
`

type CreateIncomeParams struct {
	UserID      int32
	CategoryID  pgtype.Int4
	IncomeDate  pgtype.Date
	Amount      pgtype.Numeric
	Description pgtype.Text
}

func (q *Queries) CreateIncome(ctx context.Context, arg CreateIncomeParams) (Income, error) {
	row := q.db.QueryRow(ctx, createIncome,
		arg.UserID,
		arg.CategoryID,
		arg.IncomeDate,
		arg.Amount,
		arg.Description,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.IncomeDate,
		&i.Amount,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIncome = `-- name: DeleteIncome :exec
DELETE FROM incomes
WHERE id = $1
`

func (q *Queries) DeleteIncome(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteIncome, id)
	return err
}

const getAllIncomes = `-- name: GetAllIncomes :many
SELECT id, user_id, category_id, income_date, amount, description, created_at, updated_at FROM incomes WHERE user_id = $1 ORDER BY income_date DESC
`

func (q *Queries) GetAllIncomes(ctx context.Context, userID int32) ([]Income, error) {
	rows, err := q.db.Query(ctx, getAllIncomes, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Income
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CategoryID,
			&i.IncomeDate,
			&i.Amount,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIncome = `-- name: GetIncome :one
SELECT id, user_id, category_id, income_date, amount, description, created_at, updated_at FROM incomes WHERE id = $1 LIMIT 1
`

func (q *Queries) GetIncome(ctx context.Context, id int32) (Income, error) {
	row := q.db.QueryRow(ctx, getIncome, id)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.IncomeDate,
		&i.Amount,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIncome = `-- name: UpdateIncome :one
UPDATE incomes
SET category_id = $2,
	income_date = $3,
	amount = $4,
	description = $5,
	updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, category_id, income_date, amount, description, created_at, updated_at
`

type UpdateIncomeParams struct {
	ID          int32
	CategoryID  pgtype.Int4
	IncomeDate  pgtype.Date
	Amount      pgtype.Numeric
	Description pgtype.Text
}

func (q *Queries) UpdateIncome(ctx context.Context, arg UpdateIncomeParams) (Income, error) {
	row := q.db.QueryRow(ctx, updateIncome,
		arg.ID,
		arg.CategoryID,
		arg.IncomeDate,
		arg.Amount,
		arg.Description,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CategoryID,
		&i.IncomeDate,
		&i.Amount,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
