// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	CreateIncome(ctx context.Context, arg CreateIncomeParams) (Income, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteExpense(ctx context.Context, id int32) error
	DeleteIncome(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id int32) error
	GetAllExpenses(ctx context.Context, userID int32) ([]Expense, error)
	GetAllIncomes(ctx context.Context, userID int32) ([]Income, error)
	GetAllUsers(ctx context.Context) ([]User, error)
	GetAllUsersWithDeleted(ctx context.Context) ([]User, error)
	GetExpense(ctx context.Context, id int32) (Expense, error)
	GetIncome(ctx context.Context, id int32) (Income, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserById(ctx context.Context, id int32) (User, error)
	HardDeleteUser(ctx context.Context, id int32) error
	RestoreUser(ctx context.Context, id int32) (User, error)
	UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error)
	UpdateIncome(ctx context.Context, arg UpdateIncomeParams) (Income, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
